- name: Create Odoo system user
  user:
    name: "odoo"
    home: "{{ odoo_dir }}"
    create_home: yes
    system: yes

- name: Create required directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ odoo_user }}"
    group: "{{ odoo_user }}"
    mode: "0755"
  loop:
    - "{{ odoo_dir }}"
    - "{{ custom_addons_dir }}"
    - "{{ enterprise_addons_dir }}"

  # Jika Odoo utama berupa ZIP
- name: Extract Odoo core from zip if provided
  unarchive:
    src: "/tmp/{{ odoo_core_file }}"
    dest: "{{ odoo_dir }}"
    remote_src: no
    extra_opts: [--strip-components=1]
  when: odoo_core_file != ""
  
# Jika ingin pakai Git Odoo seperti biasa
- name: Clone Odoo source from Git
  git:
    repo: "https://github.com/odoo/odoo"
    dest: "{{ odoo_dir }}"
    version: "{{ odoo_version }}"
    depth: 1
    force: yes
  become_user: "{{ odoo_user }}"
  when: odoo_core_file == ""


- name: Setup Python venv
  command: python3 -m venv {{ odoo_dir }}/venv
  args: { creates: "{{ odoo_dir }}/venv" }

- name: Install Python requirements
  pip:
    requirements: "{{ odoo_dir }}/requirements.txt"
    virtualenv: "{{ odoo_dir }}/venv"

- name: Extract custom addons if provided
  unarchive:
    src: "/tmp/{{ addons_file }}"
    dest: "{{ custom_addons_dir }}"
    remote_src: no
  when: addons_file != ""

- name: Extract enterprise addons if provided
  unarchive:
    src: "/tmp/{{ enterprise_addons_file }}"
    dest: "{{ enterprise_addons_dir }}"
    remote_src: no
  when: enterprise_addons_file != ""

- name: Clone custom addons repo if provided
  git:
    repo: "{{ addons_repo_url }}"
    dest: "{{ custom_addons_dir }}"
    version: "{{ addons_repo_branch }}"
  when: addons_repo_url != ""
