---
- name: Install odoo
  hosts: target_hosts
  become: yes
  gather_facts: yes

  roles:
    - common
    - postgersql
    - odoo
    - role: nginx
      when: install_nginx | bool
    - role: odoo_database
      when: create_database | bool

  post_tasks:
    - name: Display Installation Summary
      debug:
        msg: |
          Odoo Installation Complete!

          Odoo URL: http{% if install_nginx | bool and install_ssl | bool %}s{% endif %}://{{ odoo_url | default(ansible_default_ipv4.address) }}{% if not install_nginx | bool %}:{{ odoo_port }}{% endif %}
          Master Password: {{ odoo_master_password }} (Keep this secured)

          {% if create_database | bool %}
          Database Info:
          - Database Name: {{ odoo_db_name }}
          - Login Username: {{ odoo_username }}
          - Login Password: {{ odoo_admin_password }}
          {% endif %}
