---
- name: Install odoo
  hosts: target_hosts
  become: yes
  gather_facts: yes
  vars:
    ansible_become_flags: "-n"

  roles:
    - common
    - postgersql
    - odoo
    - role: nginx
      when: install_nginx | bool
    - role: odoo_database
      when: create_database | bool
    - role: deploy_scripts
      when: deploy_scripts | bool
