- name: Update apt cache
  apt:
    update_cache: yes

- name: Install dependencies
  apt:
    name:
      - git
      - python3-pip
      - python3-venv
      - python3-dev
      - libxml2-dev
      - libxslt1-dev
      - zlib1g-dev
      - libsasl2-dev
      - libldap2-dev
      - build-essential
      - libssl-dev
      - libffi-dev
      - libjpeg-dev
      - libpq-dev
      - npm
      - node-less
    state: present

- name: Install less dependencies
  npm:
    name:
      - less
      - less-plugin-clean-css
    global: yes

- name: Install wkhtmltopdf
  apt:
    name: wkhtmltopdf
    state: present
