---
- name: Update package lists
  apt:
    update_cache: yes

- name: Upgrade packages
  apt:
    upgrade: dist

- name: Autoremove unused packages
  apt:
    autoremove: yes
    purge: yes

- name: Clean up APT Cache
  apt:
    autoclean: yes

- name: Install Odoo system dependencies
  apt:
    name:
      - acl
      - python3-pip
      - python3-dev
      - python3-wheel
      - python3-psycopg2
      - build-essential
      - wget
      - unzip
      - zip
      - git
      - libxslt1-dev
      - libzip-dev
      - libldap2-dev
      - libsasl2-dev
      - libssl-dev
      - node-less
      - libjpeg-dev
      - zlib1g-dev
      - liblcms2-dev
      - libxml2-dev
      - libjpeg8-dev
      - libpq-dev
      - libffi-dev
      - nodejs
      - npm
      # Opsional / tambahan
      - libblas-dev
      - libatlas-base-dev
      # Untuk Ubuntu 20.04 (deprecated di 22.04+)
      - "{{ 'libssl1.1' if ansible_distribution_version is version('22.04', '<') else 'libssl3' }}"
    state: present
    update_cache: yes
  notify:
    - apt_clean

- name: Install build deps for cryptography
  apt:
    name:
      - build-essential
      - libssl-dev
      - libffi-dev
      - python3-dev
      - cargo
      - rustc
      - pkg-config
    state: present
    update_cache: yes

- meta: flush_handlers

- name: Get Python version
  command: python3 -c "import platform; print(platform.python_version())"
  register: python_version

- name: Install matching python venv package
  become: yes
  apt:
    name: "python{{ python_version.stdout.split('.')[0] }}.{{ python_version.stdout.split('.')[1] }}-venv"
    state: present

- name: Set timezone to UTC
  timezone:
    name: UTC
